### ISSUE TITLE
why cant say chinese

### ISSUE THREAD

**Issue by yiaxon1021** [MrDiamond64/Scythe-AntiCheat#55]
why cant say chinese

**Comment by MrDiamond64** [comment]
Can you explain further?

**Comment by w45466920300** [comment]
That is, when you load this addon in the archive, and enter Chinese characters, Chinese phonetic symbols, Japanese Hiragana and Katakana, Korean and other East Asian symbols in the chat bar, it will not be displayed when sent. Below are a few examples.
When you enter the Chinese character "你好" (Hello)in the chat bar, only <your name> will be displayed on the screen without any words after it. If I type something like "你会在Minecraft里玩2b2t吗"(Will you play 2b2t in Minecraft), it will only show
 <your name>   Minecraft   2b2t
This shouldn't be a problem with game rendering, because it does affect communication in multiplayer games, others don't know what you're talking about, and others can't see the characters you type.

**Comment by w45466920300** [comment]
That is, when you load this addon in the archive, and enter Chinese characters, Chinese phonetic symbols, Japanese Hiragana and Katakana, Korean and other East Asian symbols in the chat bar, it will not be displayed when sent. Below are a few examples.
When you enter the Chinese character "你好" (Hello)in the chat bar, only <your name> will be displayed on the screen without any words after it. If I type something like "你会在Minecraft里玩2b2t吗"(Will you play 2b2t in Minecraft), it will only show
 <your name>   Minecraft   2b2t
This shouldn't be a problem with game rendering, because it does affect communication in multiplayer games, others don't know what you're talking about, and others can't see the characters you type.

**Comment by w45466920300** [comment]
That is, when you load this addon in the archive, and enter Chinese characters, Chinese phonetic symbols, Japanese Hiragana and Katakana, Korean and other East Asian symbols in the chat bar, it will not be displayed when sent. Below are a few examples.
When you enter the Chinese character "你好" (Hello)in the chat bar, only 〈your name>〉will be displayed on the screen without any words after it. If I type something like "你会在Minecraft里玩2b2t吗"(Will you play 2b2t in Minecraft), it will only show
 〈your name〉   Minecraft   2b2t
This shouldn't be a problem with game rendering, because it does affect communication in multiplayer games, others don't know what you're talking about, and others can't see the characters you type.

**Comment by MrDiamond64** [comment]
> That is, when you load this addon in the archive, and enter Chinese characters, Chinese phonetic symbols, Japanese Hiragana and Katakana, Korean and other East Asian symbols in the chat bar, it will not be displayed when sent. Below are a few examples. When you enter the Chinese character "你好" (Hello)in the chat bar, only 〈your name>〉will be displayed on the screen without any words after it. If I type something like "你会在Minecraft里玩2b2t吗"(Will you play 2b2t in Minecraft), it will only show 〈your name〉 Minecraft 2b2t This shouldn't be a problem with game rendering, because it does affect communication in multiplayer games, others don't know what you're talking about, and others can't see the characters you type.

Thanks. I have managed to replicate and fix the issue.

Scythe has an option to filter characters out like that as users were using them to lag peoples games. The feature was later disabled default due to a complaint on MCPEDL that they couldnt speak in their language.

A bug within the addon made it filter characters out regardless wether it was disabled or not.
You can fix the issue by replacing line 52 in `./<pack data>/scripts/main.js` with this:
`} else if(player.name === player.nameTag && config.modules.filterUnicodeChat && msg.cancel === false) {`
